### ISSUE TITLE
Start the app and daemon on Login

### ISSUE THREAD

**Issue by krl** [ipfs-shipyard/ipfs-station#15]
An opt-in option for platform-specific startup scripts.

**Comment by jbenet** [comment]
The original comment was https://github.com/ipfs/electron-app/pull/13#discussion_r32900249

> Separately, i think we want to add two checkboxes to this initial "setup dialog":
>
> - [ ] Add IPFS Node to Login Items[0]. This opens the IPFS menubar item. If it is switched to "On", it will also start your IPFS Node.[1]
>
> [0] this is platform specific. may need different language per platform.
> [1] there's got to be a better, simpler way to say this. the tricky part is it must capture (a) the on/off switch, (b) "IPFS Node" app remembering the state user left it in (on/off), (c) that it will start the IPFS node iff the node was left "On". (all without being too verbose. design is hard :) ).

not sure if we mean the same thing ("persist instance between reboots"). i just mean an option for the daemon to be launched on startup
