### ISSUE TITLE
Two buttons for the same thing

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-station#560]
Right now we have two different buttons doing the same thing: turning the daemon on and off.

![image](https://user-images.githubusercontent.com/5447088/34267228-03f7c42e-e674-11e7-84fe-c9e7bc02c2b1.png)

Should they be kept? IMO, we should remove the one from the bottom since it's repetitive. Although, it's more clear what it does than the one from the top right.

/cc @diasdavid

**Comment by machawk1** [comment]
Is there sufficient distinction in the UI whether each button closes IPFS station or quits the IPFS daemon? I see the cube and I think "IPFS interaction" whereas a Power Symbol on an app would indicate closing the app itself (albeit, it cannot be "toggled" again to turn the app back on like hardware).
